# AUTOGENERATED! DO NOT EDIT! File to edit: ../app.ipynb.

# %% auto 0
__all__ = ['learn', 'categories', 'image', 'label', 'examples', 'intf', 'classify_image']

# %% ../app.ipynb 1
from fastai.vision.all import *
import gradio as gr
import fastbook
from fastbook import *
from fastai.vision.widgets import *

# %% ../app.ipynb 3
learn = load_learner('export.pkl')


# %% ../app.ipynb 5
categories = ( 'Captain America', 'Hawkeye', 'Hulk', 'Iron Man', 'Natasha Romanoff', 'Thor')

def classify_image(img):
  pred, idx, prob = learn.predict(img)
  return dict(zip(categories, map(float, prob)))

# %% ../app.ipynb 7
image = gr.Image()
label = gr.Label()
examples = ['hulk.jpg', 'ironman.jpg', 'captainamerica.jpg']

intf = gr.Interface(fn = classify_image, inputs = image, outputs = label, examples = examples)
intf.launch(inline = False)
